---
 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 name: Chart Builder
 
 on:
   workflow_call:
     inputs:
       name:
         type: string
         description: Chart Name
         required: true
       version:
         type: string
         description: Chart Version
         required: true
       registry:
         type: string
         description: Chart Registry
         required: true
       release:
         type: boolean
         description: Release
         required: true
 
 jobs:
   prepare:
     name: Prepare
     runs-on: ubuntu-latest
     outputs:
       chart-exists: ${{ steps.chart.outputs.exists }}
     steps:
       - name: Checkout
         uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
 
       - name: Setup Vars
         uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
         id: vars
         with:
           script: |
             core.setOutput('repository', '${{ github.repository }}'.toLowerCase());
             core.setOutput('repository-name', '${{ github.repository }}'.split('/').pop().toLowerCase());
 
       - name: Check For Exising Chart
         uses: ./.github/actions/chart-exists
         id: chart
         with:
           chart: ${{ steps.vars.outputs.repository-name }}/${{ inputs.name }}
 
   build:
     name: Build (${{ inputs.version }})
     runs-on: ubuntu-latest
     needs: ["prepare"]
     steps:
       - name: Setup Vars
         uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
         id: vars
         with:
           script: |
             core.setOutput('repository', '${{ github.repository }}'.toLowerCase());
             core.setOutput('repository-name', '${{ github.repository }}'.split('/').pop().toLowerCase());
 
       - name: Install Helm
         uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
 
       - if: ${{ inputs.release }}
         name: Install Cosign
         uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
 
       - if: ${{ inputs.release }}
         name: Login to GitHub Container Registry
         uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ github.token }}
 
       - name: Add Helm Repository
         run: |
           helm repo add upstream ${{ inputs.registry }}
 
       - name: Update Helm Repository
         run: |
           helm repo update upstream
 
       - name: Pull Chart
         run: |
           helm pull upstream/${{ inputs.name }} --version ${{ inputs.version }}
 
       - if: ${{ inputs.release }}
         name: Push Chart
         run: |
           helm push *.tgz oci://ghcr.io/${{ steps.vars.outputs.repository }}
 
       - if: ${{ inputs.release }}
         name: Sign artifacts with Cosign
         run: |
           cosign sign --yes ghcr.io/${{ steps.vars.outputs.repository }}/${{ inputs.name }}:${{ inputs.version }}
 
   release:
     if: ${{ inputs.release && needs.prepare.outputs.chart-exists != 'true' }}
     name: Release
     needs: ["prepare", "build"]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
 
       - name: Setup Vars
         uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
         id: vars
         with:
           script: |
             core.setOutput('repository', '${{ github.repository }}'.toLowerCase());
             core.setOutput('repository-name', '${{ github.repository }}'.split('/').pop().toLowerCase());
 
       - name: Generate Token
         uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
         id: app-token
         with:
           app-id: ${{ secrets.BOT_APP_ID }}
           private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
 
       - name: Get Release Tag
         uses: ./.github/actions/release-tag
         id: release
         with:
           token: ${{ steps.app-token.outputs.token }}
 
       - name: Create Release
         uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
         with:
           body: |
             > [!NOTE]
             > A new chart has been added.
 
             ## 📦 Chart
 
             **Name**: [${{ inputs.name }}](https://github.com/${{ github.repository }}/pkgs/container/${{ steps.vars.outputs.repository-name }}%2F${{ inputs.name }})
           tag: ${{ steps.release.outputs.tag }}
           token: ${{ steps.app-token.outputs.token }}
 
   notify:
     if: ${{ inputs.release && !cancelled() }}
     needs: ["prepare", "build", "release"]
     name: Notify
     runs-on: ubuntu-latest
     steps:
       - if: ${{ contains(needs.*.result, 'failure') }}
         name: Send Discord Webhook
         uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008 # v1.15.3
         with:
           color: "0xFF0000"
           description: |
             Name: `${{ inputs.name }}`
             Version: `${{ inputs.version }}`
             [Rebuild](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yaml)
           nodetail: true
           title: Chart build failed
           username: GitHub Actions
           url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           webhook: ${{ secrets.DISCORD_WEBHOOK }}